import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');
const model = genAI.getGenerativeModel({ model: 'gemma-4-31b-it' });

const BASE64_DATA = "JVBERi0xLjUKJeLjz9MKNSAwIG9iago8PC9Db2xvclNwYWNlL0RldmljZVJHQi9TdWJ0eXBlL0ltYWdlL0hlaWdodCAxNTYvRmlsdGVyL0RDVERlY29kZS9UeXBlL1hPYmplY3QvV2lkdGggMTI0MC9CaXRzUGVyQ29tcG9uZW50IDgvTGVuZ3RoIDQ0NTY4Pj5zdHJlYW0K/9j/4AAQSkZJRgABAgAAZABkAAD/7AARRHVja3kAAQAEAAAAZAAA/+4ADkFkb2JlAGTAAAAAAf/bAIQAAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQICAgICAgICAgICAwMDAwMDAwMDAwEBAQEBAQECAQECAgIBAgIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMD/8AAEQgAnATYAwERAAIRAQMRAf/EANMAAQADAQADAQEBAAAAAAAAAAAICQoHBQYLBAIDAQEAAgMAAwEBAAAAAAAAAAAABgcEBQgCAwkKARAAAAcBAAEDAgQCBgYGCAcAAAECAwQFBgcIERIJExQhIhUKMRZRI7YXdzhBMkIztHZhJCW1NxhSYjRVl9c5GrOU1HU2VygRAAICAQIDBQMGCQgHBgQHAQABAgMEEQUhEgYxQVETB2EiCHGBkaEyFLHBQnKyIxU1CdFSgpIzcyQW8GKiwkNTNOF0tHUXN9KzRTjDJbU2VnZ3Of/aAAwDAQACEQMRAD8A38AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

const PROMPT = `You are a financial parsing engine. Analyze the following document and extract structured transaction information.
    For each valid financial transaction found:
    - Identify the date (formatted as YYYY-MM-DD). Assume 2026.
    - Extract the transaction amount as a positive number.
    - Classify the type as "expense" or "income".
    - Categorify it (Food, Transport, Shopping, Rent, etc.).
    - Provide a short, clean description.
    
    Return a JSON response with this EXACT structure:
    [
      {
        "date": "YYYY-MM-DD",
        "amount": number,
        "type": "expense" | "income",
        "category": "string",
        "description": "string"
      }
    ]`;

async function run() {
  try {
    const result = await model.generateContent([
      {
        inlineData: {
          data: BASE64_DATA,
          mimeType: 'application/pdf'
        }
      },
      PROMPT
    ]);
    console.log(result.response.text());
  } catch (e) {
    console.error(e.message);
  }
}

run();
